### ISSUE TITLE
Tutorial markdown missing some useful information

### ISSUE THREAD

**Issue by stenhuisen** [phys201/bayboone#24]
I would have appreciated having a few of the "obvious" variable names defined, especially numu and nue. 

A few other things were a little unclear to me in the tutorial. For example, why are you simulating both microboone and "generic" data? And what is meant by "generic" data?/how is it different from microboone data?

Lastly, just a question: Why draw sin^2(2 theta) from a uniform distribution instead of theta itself? I see why it's programmatically more convenient, but since sine is not a linear function, does this not distort somewhat the results?

**Comment by tcontrer** [comment]
More clearly explained the variables and data in the tutorial notebook. Updated the priors in the inference. #29
