### ISSUE TITLE
function in __init__.py

### ISSUE THREAD

**Issue by jennmcguire** [phys201/bayboone#41]
You have a function in your __init__.py file that shouldn't be there. It is unclear what the purpose of the function is. It is labeled test, but isn't a unit test because it returns something and won't be found by nosetests in its current location. In general, non-unit testing functions should not have the word "test" in the name to avoid confusion. You should remove this function or clarify what the purpose is if you feel the need to include it.

```
def test_git():
    print("Hello World!")
    return True
```

**Comment by tcontrer** [comment]
Deleted in #43
